### ISSUE TITLE
EDTF output

### ISSUE THREAD

**Issue by Javarome** [nicompte/edtfy#1]
Thank you for this amazing work, especially the i18n aspect of it.

As EDTF is typically used for storage, I think most users will also need the API to output the human-readable display of such EDTF data on the client/browser side. Do you plan that feature?

Thanks.

**Comment by nicompte** [comment]
Hello Javarome, 

Thanks for your interest in edtfy. The feature your ask for will be part of another project, [unedtfy](https://github.com/nicompte/unedtfy), so I'll close this issue for now, but stay tuned!
