### ISSUE TITLE
certain valid inputs throw syntax error

### ISSUE THREAD

**Issue by coherit** [nicompte/edtfy#2]
Super work on this parser -- it's extremely handy! 

I'm getting a syntax error when passing certain valid dates that meet edtf standards and was wondering if this was expected behavior (and if you have a suggested way for me to handle this while still catching "real"/un-parseable errors). 

For instance:
If a user inputs "1892", edtfy returns the string with no error (=great!).

If a user inputs "around 1892", edtfy returns 1892~ (=awesome!).

If a user inputs "1892~", edtfy throws:

```
peg$SyntaxError {message: "Expected " ", " / ", " A ", " B2 ", " C", " O ", "…", "u", "x", [0-9]
or end of input but "~" found.", expected: Array[13], found: "~",
location: Object, name: "SyntaxError"}
```

which I didn't expect (I was expecting it to just pass the string back to me). 

Similarly, if a user inputs "open", it throws a similar peg error:

```
peg$SyntaxError {message: "Expected " ", " / ", " A ", " B2 ", " O ", "*", "-…, [0-9], [ivxlcdm]
or end of input but "O" found.", expected: Array[22], found: "O",
location: Object, name: "SyntaxError"}
```

I checked with "1892?" and edtfy passes the string back to me, which was what I was expecting with "1892~". 

Am I missing something? Thanks!

**Comment by nicompte** [comment]
Thanks for your feedback @coherit!

The parsing errors you have are expected, although maybe also an error :)

English is not my primary language (French), and `1892~` is not a form we'd use, but rather `~1892`, which works with the parser. Do you think I should add `date~`?

Regarding the `open` issue, I couldn't find on the specification where it could be used without an interval context, `5.2.3. Extended Interval (L1)`, so something like `march 1992 - open`, which is correctly parsed, or `after march 1992`. What kind of date form did you intend to parse?

By the way, the [website](http://edtfy.barbotte.net) works now, and you can edit the inputs for easy checking.

**Comment by coherit** [comment]
Hi Nicolas, I see now. 

According to the English version of edtf, the ~ or ? characters are only allowed after the date and not before, so perhaps you will want to add that for locale en.

As for "open," the form I am validating splits the from and to dates into separate fields, which I plan to parse separately. You are right in that I should only accept open as part of such an interval, so perhaps I will have to do some pre-validation on the pair first and not pass the open value to the parser. 

I really appreciate your quick reply, and really appreciate the work you have done!

**Comment by nicompte** [comment]
Hello Angela, I've pushed a fix, you should be able to use the `~` sign after the date, like `1892~` now :)

The fix is available on the `0.0.6` version.

**Comment by nicompte** [comment]
I'll close this issue, feel free to re-open it if necessary.

**Comment by coherit** [comment]
Sorry for my delay -- I just tested the updated version and confirmed that 1892~ (yyyy~) now works -- thanks!
